### ISSUE TITLE
Improve error message when trying to shrink Java 11 class files

### ISSUE THREAD

**Issue by Fohlen** [yWorks/yGuard#9] opened 2019-10-15 08:13 UTC
Shrinking Java 11 byte code results in

```
Buildfile: /home/behr/localhg/yguard-all/yguard/build-support.xml

shrink-wmextractor:
    [mkdir] Created dir: /home/behr/localhg/yguard-all/yguard/target/wmextractor
   [shrink] yGuard Shrinker v2.7.2-rc1 - http://www.yworks.com/products/yguard
   [shrink] parsing /home/behr/Downloads/wmextractor.jar
   [shrink] parsing /home/behr/Downloads/wmextractor.jar
   [shrink] writing shrinked /home/behr/Downloads/wmextractor.jar to /home/behr/localhg/yguard-all/yguard/target/wmextractor/wmextractor_shrinked.jar.
   [shrink] ERROR: This feature requires ASM7
   [shrink] This feature requires ASM7

BUILD FAILED
/home/behr/localhg/yguard-all/yguard/build-support.xml:175: yShrink encountered an unknown problem!

Total time: 6 seconds
```

It would probably be a good idea to configure ASM to accept Java 11 byte code instruction, track the occurrence of such instructions, and after ASM is done have yGuard abort with a sensible error message along the lines of "Shrinking is not supported for Java 11 class files" or "... class files with invokedynamic and/or nest instructions".

**Comment by lgka** [comment] 2019-10-25 09:00
I get the same error when I try to obfuscate a jar created with openjdk >=9
I notice that yguard 2.9.0 contains asm-7.2.jar but I still get this error...

**Comment by lgka** [comment] 2019-11-08 08:13
Hello, is there any workaround for the above error or planned to be fixed in a future release ? I use the latest openjdk 13.0.1

**Comment by yGuy** [comment] 2019-11-08 08:25
The project was open-sourced just recently, so the community hasn't grown, much, yet. We certainly don't have the resources to fix all open issues, immediately on our own, yet. And as much as I hate to say it, we also open-sourced it, hoping that others might step in to help with the implementation and maintenance. Sadly most open-source lovers, still only love open source because it's free, and don't want to help, either. 

That said - the fact that the issue is reported, marked as high priority gives a strong indication that there a plans for fixing it in a future release. So the answer to your question is yes, we just don't know yet, when that will happen :-)

**Closed** 2020-05-22 07:32 UTC
Labels: enhancement, priority:high
